// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vsyzncpviakqrtropebr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZzeXpuY3B2aWFrcXJ0cm9wZWJyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc5Mjc5NzIsImV4cCI6MjA3MzUwMzk3Mn0.4Dw02jeVIexPSOHL1rhmnpydNF0L1ZiNtg804Z-4rio";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});